name: hcom
description: HPCom UART debugging assistant for Windows.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  bitsdojo_window: ^0.1.6
  crypto: ^3.0.7
  file_selector: ^1.0.3
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - Image/HPCOMLOGOtouming.png
  fonts:
    - family: Cascadia Code
      fonts:
        - asset: assets/fonts/CascadiaCode-Regular.ttf
          weight: 400
        - asset: assets/fonts/CascadiaCode-SemiBold.ttf
          weight: 600
    - family: Noto Sans SC
      fonts:
        - asset: assets/fonts/NotoSansSC-VariableFont_wght.ttf
